Update patch set 10
Patch Set 10: Verified-1

(1 comment)

I am getting this when trying to extract hashtags.
I am using it with 3.1.4 API.


[2020-04-24 11:40:04,443] [HTTP-80] WARN  org.eclipse.jetty.server.HttpChannel : /a/projects/homepage/analytics~contributors
com.google.common.util.concurrent.ExecutionError: java.lang.IllegalAccessError: tried to access method com.google.gerrit.server.notedb.ChangeNotesCache.get(Lcom/google/gerrit/entities/Project$NameKey;Lcom/google/gerrit/entities/Change$Id;Lorg/eclipse/jgit/lib/ObjectId;Ljava/util/function/Supplier;)Lcom/google/gerrit/server/notedb/ChangeNotesCache$Value; from class com.google.gerrit.server.notedb.HashTagsExtractorImpl$$anonfun$hashTagsOfCommit$1$$anonfun$apply$1$$anonfun$applyOrElse$1$$anonfun$apply$6
	at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache.get(CaffeinatedGuavaLoadingCache.java:67)
	at com.googlesource.gerrit.plugins.analytics.common.CommitsStatisticsCacheImpl.get(CommitsStatisticsCache.scala:37)
	at com.googlesource.gerrit.plugins.analytics.common.Statistics$$anonfun$5.apply(CommitsStatistics.scala:92)
	at com.googlesource.gerrit.plugins.analytics.common.Statistics$$anonfun$5.apply(CommitsStatistics.scala:92)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.googlesource.gerrit.plugins.analytics.common.Statistics.forCommits(CommitsStatistics.scala:92)
	at com.googlesource.gerrit.plugins.analytics.UserActivitySummary$.apply(Contributors.scala:184)
	at com.googlesource.gerrit.plugins.analytics.ContributorsService$$anonfun$get$1$$anonfun$apply$2.apply(Contributors.scala:149)
	at com.googlesource.gerrit.plugins.analytics.ContributorsService$$anonfun$get$1$$anonfun$apply$2.apply(Contributors.scala:149)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:186)
	at com.googlesource.gerrit.plugins.analytics.ContributorsService$$anonfun$get$1.apply(Contributors.scala:149)
	at com.googlesource.gerrit.plugins.analytics.ContributorsService$$anonfun$get$1.apply(Contributors.scala:144)
	at com.googlesource.gerrit.plugins.analytics.common.ManagedResource$.use(ManagedResources.scala:20)
	at com.googlesource.gerrit.plugins.analytics.ContributorsService.get(Contributors.scala:144)
	at com.googlesource.gerrit.plugins.analytics.ContributorsResource.apply(Contributors.scala:127)
	at com.googlesource.gerrit.plugins.analytics.ContributorsResource.apply(Contributors.scala:80)
	at com.google.gerrit.httpd.restapi.RestApiServlet.service(RestApiServlet.java:499)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	at com.google.gerrit.httpd.raw.StaticModule$PolyGerritFilter.doFilter(StaticModule.java:436)
	at com.google.gerrit.httpd.GetUserFilter.doFilter(GetUserFilter.java:92)
	at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:120)
	at com.google.gerrit.httpd.RequireIdentifiedUserFilter.doFilter(RequireIdentifiedUserFilter.java:50)
	at com.google.gerrit.httpd.SetThreadNameFilter.doFilter(SetThreadNameFilter.java:62)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:133)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:135)
	at com.google.gerrit.httpd.RequestCleanupFilter.doFilter(RequestCleanupFilter.java:60)
	at com.google.gerrit.httpd.ProjectBasicAuthFilter.doFilter(ProjectBasicAuthFilter.java:101)
	at com.google.gerrit.httpd.RequestMetricsFilter.doFilter(RequestMetricsFilter.java:57)
	at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:64)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalAccessError: tried to access method com.google.gerrit.server.notedb.ChangeNotesCache.get(Lcom/google/gerrit/entities/Project$NameKey;Lcom/google/gerrit/entities/Change$Id;Lorg/eclipse/jgit/lib/ObjectId;Ljava/util/function/Supplier;)Lcom/google/gerrit/server/notedb/ChangeNotesCache$Value; from class com.google.gerrit.server.notedb.HashTagsExtractorImpl$$anonfun$hashTagsOfCommit$1$$anonfun$apply$1$$anonfun$applyOrElse$1$$anonfun$apply$6
	at com.google.gerrit.server.notedb.HashTagsExtractorImpl$$anonfun$hashTagsOfCommit$1$$anonfun$apply$1$$anonfun$applyOrElse$1$$anonfun$apply$6.apply(HashTagsExtractorImpl.scala:76)
	at com.google.gerrit.server.notedb.HashTagsExtractorImpl$$anonfun$hashTagsOfCommit$1$$anonfun$apply$1$$anonfun$applyOrElse$1$$anonfun$apply$6.apply(HashTagsExtractorImpl.scala:80)
	at scala.util.Try$.apply(Try.scala:192)
	at com.google.gerrit.server.notedb.HashTagsExtractorImpl$$anonfun$hashTagsOfCommit$1$$anonfun$apply$1$$anonfun$applyOrElse$1.apply(HashTagsExtractorImpl.scala:74)
	at com.google.gerrit.server.notedb.HashTagsExtractorImpl$$anonfun$hashTagsOfCommit$1$$anonfun$apply$1$$anonfun$applyOrElse$1.apply(HashTagsExtractorImpl.scala:70)
	at scala.Option.map(Option.scala:146)
	at com.google.gerrit.server.notedb.HashTagsExtractorImpl$$anonfun$hashTagsOfCommit$1$$anonfun$apply$1.applyOrElse(HashTagsExtractorImpl.scala:70)
	at com.google.gerrit.server.notedb.HashTagsExtractorImpl$$anonfun$hashTagsOfCommit$1$$anonfun$apply$1.applyOrElse(HashTagsExtractorImpl.scala:66)
	at scala.collection.TraversableOnce$class.collectFirst(TraversableOnce.scala:145)
	at scala.collection.AbstractTraversable.collectFirst(Traversable.scala:104)
	at com.google.gerrit.server.notedb.HashTagsExtractorImpl$$anonfun$hashTagsOfCommit$1.apply(HashTagsExtractorImpl.scala:66)
	at com.google.gerrit.server.notedb.HashTagsExtractorImpl$$anonfun$hashTagsOfCommit$1.apply(HashTagsExtractorImpl.scala:63)
	at scala.Option.map(Option.scala:146)
	at com.google.gerrit.server.notedb.HashTagsExtractorImpl.hashTagsOfCommit(HashTagsExtractorImpl.scala:63)
	at com.googlesource.gerrit.plugins.analytics.common.CommitsStatisticsLoader$$anonfun$load$1$$anonfun$apply$2.apply(CommitsStatisticsLoader.scala:90)
	at com.googlesource.gerrit.plugins.analytics.common.CommitsStatisticsLoader$$anonfun$load$1$$anonfun$apply$2.apply(CommitsStatisticsLoader.scala:59)
	at com.googlesource.gerrit.plugins.analytics.common.ManagedResource$.use(ManagedResources.scala:20)
	at com.googlesource.gerrit.plugins.analytics.common.CommitsStatisticsLoader$$anonfun$load$1.apply(CommitsStatisticsLoader.scala:59)
	at com.googlesource.gerrit.plugins.analytics.common.CommitsStatisticsLoader$$anonfun$load$1.apply(CommitsStatisticsLoader.scala:55)
	at com.googlesource.gerrit.plugins.analytics.common.ManagedResource$.use(ManagedResources.scala:20)
	at com.googlesource.gerrit.plugins.analytics.common.CommitsStatisticsLoader.load(CommitsStatisticsLoader.scala:55)
	at com.googlesource.gerrit.plugins.analytics.common.CommitsStatisticsLoader.load(CommitsStatisticsLoader.scala:34)
	at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache$SingleLoader.load(CaffeinatedGuavaLoadingCache.java:136)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:140)
	at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:139)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2379)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2377)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2360)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)
	at com.github.benmanes.caffeine.guava.CaffeinatedGuavaLoadingCache.get(CaffeinatedGuavaLoadingCache.java:59)
	... 73 more

Patch-set: 10
Reviewer: Gerrit User 1054778 <1054778@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1